# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200228_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
